### ISSUE TITLE
Wrong version getting/got built

### ISSUE THREAD

**Issue by 5kt** [gardenlinux/package-curl#1]
**What happened**:
Currently, with no special configuration, curl 8.9 is getting built, but unfortunately this is the wrong version, the proper version is 8.8 (coming from testing). 
The issue seems to stem from the fact that the Debian sources repository for _testing_ includes both 8.8 and 8.9 source versions - 8.9 gets pulled when fetching the source as it's the higher version.

**What you expected to happen**:
curl 8.8 should get built.

**How to reproduce**
Use _ghcr.io/gardenlinux/repo-debian-snapshot_, actually _sha256:887d347f4a418eaeeb2d6e12c0bb5840482b3a07a7895a9a695d7539eb6afc77_
```
root@478ce462be91:/# cat /etc/apt/sources.list
deb https://dqf78g7gefsor.cloudfront.net/debian-snapshot 1723580387 main
deb-src https://dqf78g7gefsor.cloudfront.net/debian-snapshot 1723580387 main
root@478ce462be91:/# apt-cache policy curl
curl:
  Installed: (none)
  Candidate: 8.8.0-4
  Version table:
     8.8.0-4 500
        500 https://dqf78g7gefsor.cloudfront.net/debian-snapshot 1723580387/main amd64 Packages
root@478ce462be91:/# apt-cache showsrc curl | grep Version
Version: 8.8.0-4
Standards-Version: 4.6.2
Version: 8.9.1-2
Standards-Version: 4.7.0
```

NOTE: as of August 18, curl 8.9 got migrated to testing, but the issue still stands as before August 18 we've built the wrong version.

**Comment by Vincinator** [comment]
Should be addressed with https://github.com/gardenlinux/package-build/pull/7
